# =================================================================================================
# Name: Civic Legislative Stack - Docker Compose
# Date: 2025-09-09
# File: docker-compose.yml
# Version: 0.3.0
# Log Summary:
#   - Adds PostgreSQL (pgvector), optional Neo4j, LocalAI, API service, optional Supabase core.
# Description:
#   Declarative multi-service stack for ingestion, storage, retrieval, summarization.
# Change Summary:
#   Initial compose for PG-focused architecture.
# Inputs:
#   Environment from .env (POSTGRES_* credentials, GOVINFO_API_KEY, OPENSTATES_API_KEY, etc.)
# Outputs:
#   Running containers, persisted volumes.
# =================================================================================================
version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: civic_pg
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  localai:
    image: localai/localai:latest
    container_name: localai
    restart: unless-stopped
    environment:
      - DEBUG=false
    volumes:
      - ./models:/models
    ports:
      - "8080:8080"

  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civic_api
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMBED_MODEL: all-MiniLM-L6-v2
      LOCALAI_ENDPOINT: http://localai:8080/v1
      GOVINFO_API_KEY: ${GOVINFO_API_KEY}
      OPENSTATES_API_KEY: ${OPENSTATES_API_KEY}
      ENABLE_NEO4J: "1"
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    depends_on:
      - postgres
      - localai
      - neo4j
    volumes:
      - ./data:/app/data
    command: >
      sh -c "python civic_legis_stack.py
             --init-db
             --sync-govinfo --govinfo-collections BILLSTATUS,PLAW --govinfo-days 7
             --sync-openstates --openstates-states 'California,New York'
             --embed
             --serve --port 8090"
    ports:
      - "8090:8090"

  # Optional Supabase (light subset). Full self-host involves additional services (kong, auth, studio).
  # This block is a placeholder referencing official docs; commented out for minimal footprint.
  # supabase-db:
  #   image: supabase/postgres
  #   ...

volumes:
  pg_data:
  neo4j_data:
  neo4j_logs: