# =================================================================================================
# Name: Docker Publish
# Date: 2025-09-09
# Script Name: docker-publish.yml
# Version: 0.5.0
# Log Summary: Builds and publishes container image on release.
# Description: Automatic Docker build & push (configure registry secrets).
# Change Summary: Initial version.
# Inputs: REGISTRY, IMAGE_NAME secrets
# Outputs: Published image
# =================================================================================================
name: docker-publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
           

          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}